services:
  controller:
    build: .
    container_name: tecmfs-controller
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads

  disk1:
    build: .
    container_name: tecmfs-disk1
    command:
      - python3
      - /app/disk_node.py
      - /app/disk_node_config.xml
    ports:
      - "8001:8001"
    volumes:
      - disk1-data:/data
      - ./src/controller/disk_nodes/simulated_disks/disk_1/disk_node.py:/app/disk_node.py
      - ./src/controller/disk_nodes/simulated_disks/disk_1/disk_node_config.xml:/app/disk_node_config.xml

  disk2:
    build: .
    container_name: tecmfs-disk2
    command:
      - python3
      - /app/disk_node.py
      - /app/disk_node_config.xml
    ports:
      - "8002:8002"
    volumes:
      - disk2-data:/data
      - ./src/controller/disk_nodes/simulated_disks/disk_2/disk_node.py:/app/disk_node.py
      - ./src/controller/disk_nodes/simulated_disks/disk_2/disk_node_config.xml:/app/disk_node_config.xml

  disk3:
    build: .
    container_name: tecmfs-disk3
    command:
      - python3
      - /app/disk_node.py
      - /app/disk_node_config.xml
    ports:
      - "8003:8003"
    volumes:
      - disk3-data:/data
      - ./src/controller/disk_nodes/simulated_disks/disk_3/disk_node.py:/app/disk_node.py
      - ./src/controller/disk_nodes/simulated_disks/disk_3/disk_node_config.xml:/app/disk_node_config.xml

  disk4:
    build: .
    container_name: tecmfs-disk4
    command:
      - python3
      - /app/disk_node.py
      - /app/disk_node_config.xml
    ports:
      - "8004:8004"
    volumes:
      - disk4-data:/data
      - ./src/controller/disk_nodes/simulated_disks/disk_4/disk_node.py:/app/disk_node.py
      - ./src/controller/disk_nodes/simulated_disks/disk_4/disk_node_config.xml:/app/disk_node_config.xml

volumes:
  disk1-data:
  disk2-data:
  disk3-data:
  disk4-data:
